paths:
  /login:
    post:
      tags:
        - Post
      summary: 登入
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: string
                  example: 'jason'
                  description: 使用者名稱
                password:
                  type: string
                  example: 'a000000'
                  description: 使用者密碼
      responses:
        '200':
          description: OK
          content:
            text:
              schema: 
                type: string
                example: 登入成功！
        '404':
          description: 如果欄位重複
          content:
            text:
              schema: 
                type: string
                example: 帳號密碼不存在！
